### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by tjbenton** [matthewbauer/plugin-raw#3]
It's not very intuitive on how you use the data that was loaded since it returns an ArrayBuffer. I would go ahead and add the following in the readme so that other people that come across this don't have to go google how to do it. There's a `TextDecoder` function that will do the same thing but it's not very well supported

Here are a few utility functions to help you dealing with `ArrayBuffers`.

``` js
// http://bit.ly/1MiLEBe
function arrayBufferToString(buf) {
  return String.fromCharCode.apply(null, new Uint8Array(buf));
}
function stringToArrayBuffer(str) {
  var buf = new ArrayBuffer(str.length * 2); // 2 bytes for each char
  var bufView = new Uint8Array(buf);
  for (var i=0, strLen= str.length; i < strLen; i++) {
    bufView[i] = str.charCodeAt(i);
  }
  return buf;
}
```

**Comment by matthewbauer** [comment]
I'm not too familiar with TextDecoder. I'm only doing stuff with raw binary data. I added a note just pointing to the MDN and the TextDecoder polyfill but I'll be willing to add anything else if you want to make a PR.
